### ISSUE TITLE
jekyllData date is converted into a mapping of integers

### ISSUE THREAD

**Issue by TeXhackse** [Witiko/markdown#114]
@Witiko I am not quite sure if this is intended. If it is just close it. I just had a look at the test file and since there is no date included it's a bit weird. 

I finally tried to update my templating engine to use your final version of the jekyll stuff (I know… took long… tough year… sorry … ) 

Currently if I add 
```
date: 2020-09-15
```
inside the jekyll header I receive the following output:
```
\markdownRendererJekyllDataMappingBegin{date}{7}
\markdownRendererJekyllDataNumber{day}{15}
\markdownRendererJekyllDataNumber{fraction}{0}
\markdownRendererJekyllDataNumber{hour}{0}
\markdownRendererJekyllDataNumber{minute}{0}
\markdownRendererJekyllDataNumber{month}{9}
\markdownRendererJekyllDataNumber{second}{0}
\markdownRendererJekyllDataNumber{year}{2020}
\markdownRendererJekyllDataMappingEnd
```
That's not what I would expect. Did you add a mechanism, to disable the datatype detection? I did not find any.

**Comment by Witiko** [comment]
@TeXhackse I will respond at length when I am not on the road, but in general: This seems to be a feature of the upstream YAML parser (for more information, see the README in the `libraries/` directory). If this behavior is undesirable, you may want to:

1. quote the date, so that is parsed as a string
2. add the option to ignore datetime literals to the upstream library

**Comment by TeXhackse** [comment]
It's not urgent at all. I just wanted to know if you want this to be enabled by default. Because I find it weird as a default behaviour for a TeX/LaTeX user. I changed it locally anyway but your default setup to use the date as `\date` would also not work this way.

**Comment by Witiko** [comment]
The upstream parser seems to implement the [timestamp data type][1]. I agree that it would be useful if the parser gave us the option of leaving timestamps alone, but I won't have much time to pursue it in the near future. If you already patched the parser for yourself, do you think you could open a pull request in the upstream library?

 [1]: https://yaml.org/type/timestamp.html

**Comment by TeXhackse** [comment]
I will have a closer look at it and keep you updated. Currently don't want to promise anything, but it helps a lot for my current usecase to know that you agree with me about this not being an optimal result.

**Comment by Witiko** [comment]
I don't have a strong dislike of it. However, timestamps are not a core data type of YAML, so it seems overly opinionated to parse them by default. I suspect that the upstream parser has been influenced by its application in Apache APISIX.

> Currently don't want to promise anything

I will get to it eventually if you don't, but it may take a couple of months before I do, so I will appreciate the help. I plan to write a TUGboat article about the YAML parser in March, so that would be a soft deadline.

**Comment by TeXhackse** [comment]
I am wondering if I miss anything because what I did so far would simply be https://github.com/TeXhackse/lua-tinyyaml/commit/2049ad66e135f81f60a7089ffad4e4b16bebbca4 I think to be able to change it globally for the library should be enough or do you think I should add the options to every part of the parser as an argument. 

Since you are a lot more familiar with Lua I thought I better ask before I create the PR on them.

**Comment by Witiko** [comment]
Instead of having a global table `options`, which will cause clashes if many different callers use the tinyyaml library, I would suggest adding an optional parameter `options` to function `parse`.

In function `parse`, we could normalize `options` to `{}` if it is `nil` and then pass `options` down the function calls. However, there are many function calls, so this last part would be especially tedious and error-prone.

A better option may be to use [a closure](https://en.wikipedia.org/wiki/Closure_(computer_programming)), which is a design pattern well-known to JavaScript programmers:

``` yaml
-------------------------------------------------------------------------------
-- tinyyaml - YAML subset parser
-------------------------------------------------------------------------------

-- all code of tinyyaml.lua except parsescalar and parse

local function parse(source, options)

  if options == nil
    options = {}
  end

  local function parsescalar(line, lines, indent)
    -- code of parsescalar, depends on options
  end

  local function parse(source)
    -- code of parse, depends on parsescalar
  end

  return parse(source)

end
```

The only disadvantage is that `tinyyaml.lua` no longer exports `parsescalar`; it is now local to the closure, which may break existing clients of the tinyyaml library and possibly also unit tests. In my opinion, that's not really an issue, since only `parse` should be the public API and `parsescalar` is an implementation detail that clients should not touch. However, I would mention it in the pull request.

**Comment by TeXhackse** [comment]
thanks. I hope it was okay to ask though you said, you're too busy. Will finish it that way.

**Comment by Witiko** [comment]
Not a problem. I am always happy to help, especially if it means that I don't have to make the pull request. 😁

**Comment by Witiko** [comment]
Enjoy the rest of the holidays and happy new year!

**Comment by TeXhackse** [comment]
What holidays? (freelancer life =P)  But I will try to to enjoy anyway. Same to you and thanks for everything I was able to learn within this project :)

Still I have a task for next year for you. Thing is due to the construction of modules in lua parsescalar has to be accessible outside the function otherwise the other parser functions cant access it. See https://github.com/TeXhackse/lua-tinyyaml/commit/b3d004b323b501a0e2f06d1f92972c69a99b93c1 

I was expecting the „global“ variable to be saved by the module construction. But I probably know too little about the details here. It would work if I move all functions into closure or add the options parameter to all of them…

**Comment by Witiko** [comment]
> Thing is due to the construction of modules in lua parsescalar has to be accessible outside the function otherwise the other parser functions cant access it.

Of course, silly me. It seems we will need to move all the `parse*` functions into the closure.

> https://github.com/TeXhackse/lua-tinyyaml/commit/b3d004b323b501a0e2f06d1f92972c69a99b93c1

Maybe we'll want to name the inner `parse` function something else (e.g. `parse_inner`) just to add clarity.

> I was expecting the „global“ variable to be saved by the module construction. But I probably know too little about the details here.

The trick is that with the closure there is no global variable. The `options` variable is a function argument, which behaves the same as local variables.

> It would work if I move all functions into closure or add the options parameter to all of them…

These are the two obvious options. The closure seems easier to implement and maintain.

**Comment by Witiko** [comment]
If you'd líke to discuss the implementation, we can talk for example at Discord (R. E. O. Speedwagon#7779).   
GitHub seems a little heavy-handed for such discussion.
