### ISSUE TITLE
Typo in File markdown.lua

### ISSUE THREAD

**Issue by Neff132** [Witiko/markdown#18]
Hey all,

I am using the markdown package with MikTeX, using the editor TexStudio.

While compiling my tex-file, I got no errors, but once I opened the pdf, where the Markdown-Output was supposed to be, there was only the message "[path]/MiKTeX/2.9/tex/luatex/markdown/markdown.lua:1212: attempt to call upvalue ’B’ (a nil value)" instead.

Checking line 1212 of markdown.lua revealed that 'B' was indeed nowhere defined at all. Instead I found a lot of instances of the function 'C' instead.
And lo, once I just tried changing the 'B' to 'C', it works perfectly (after ~10 tries with different files).
I have honestly no idea what 'C' does.

Now, I admit openly that I'm not well versed with Lua, scratch that, I have no idea at all about Lua, but this must be the most amusing and puzzling bug I've ever seen. For the moment, I'm just gonna put it down to a typo. It would be interesting to see if anyone else has/had this problem. Maybe it also has to do with how I interpreted the markdown.ins file? No idea, really.

Lines 1211-1214 of markdown.lua:

parsers.between = function(p, starter, ender)
  local ender2 = B(parsers.nonspacechar) * ender
  return (starter * #parsers.nonspacechar * Ct(p * (p - ender2)^0) * ender2)
end

Changed to:

parsers.between = function(p, starter, ender)
  local ender2 = C(parsers.nonspacechar) * ender
  return (starter * #parsers.nonspacechar * Ct(p * (p - ender2)^0) * ender2)
end

**Comment by Witiko** [comment]
`B` is defined as [`lpeg.B`](http://www.inf.puc-rio.br/~roberto/lpeg/#op-behind) on lines 100–102 of markdown.lua (lines [2003](https://github.com/Witiko/markdown/blob/master/markdown.dtx#L2003)–[2005](https://github.com/Witiko/markdown/blob/master/markdown.dtx#L2005) in [markdown.dtx](https://github.com/Witiko/markdown/blob/master/markdown.dtx)). [`lpeg.B`](http://www.inf.puc-rio.br/~roberto/lpeg/#op-behind) is very different from [`lpeg.C`](http://www.inf.puc-rio.br/~roberto/lpeg/#cap-c); it is only due to the weak typing of Lua that your modified version works at all.

It appears that your LuaTeX interpreter does not contain the `lpeg.B` method. Would you please confirm this by creating a text file named `test.lua` with the following contents:
```lua
local lpeg = require"lpeg"
print(lpeg.B)
```
and running the command `texlua test.lua` from the command line? If I am correct, the command should print the string `nil`. In that case, would you please tell me which version of LuaTeX you have installed? You can find out by running `luatex -v` from the command line; I have both version 0.95.0 (from TeX Live 2016) and 1.0.4 (from TeX Live 2017 pretest) installed and I can reproduce this issue with neither, so this could possibly point to a badly compiled binary. I am using a Linux box, so there is still the possibility that this issue is specific to the architecture of the binary.

**Comment by Neff132** [comment]
The test function produces 'nil' as expected.
My Lua version is apparently beta-0.70.2 (from MiKTeX 2.9 64-bit).

So, I guess it is very likely that this is indeed coming from the MikTeX-side. For the moment I'm gonna make do without the emphasis, and just use it like this. Thanks for the help. :)

**Comment by Witiko** [comment]
Well, as noted in Section 1.4.1 of the [package manual][man], at least LuaTeX 0.72.0 is required. The [current version of LuaTeX in the MikTeX repositories][repo] is 1.0.4, so you should probably just [update your installation][update].

 [man]: http://mirrors.ctan.org/macros/generic/markdown/markdown.pdf
 [repo]: https://miktex.org/packages/miktex-luatex-bin-x64-2.9
 [update]: https://miktex.org/howto/update-miktex
