### ISSUE TITLE
newenvironment with markdown

### ISSUE THREAD

**Issue by cdupont** [Witiko/markdown#20]
Hi, and thanks a lot for this package!
I'm trying to define a new environment with markdown:
```
\newenvironment{todo}
   {\begin{markdown}
   }
   { 
   \end{markdown}
   }
```
But I got this message:
```
Runaway argument?
! File ended while scanning use of ^^M.
```

**Comment by Witiko** [comment]
Hi. You cannot do that, since when the package encounters `\begin{markdown}`, it starts scanning for precisely the string `\end{markdown}` and there is no expansion during this procedure. You can add support as follows:

```latex
\newenvironment{todo}
    \todoenv
    \relax
```

Given the following (slightly tricky) definition of `\todoenv`:

```latex
\begingroup
\catcode`\|=0\catcode`\<=1\catcode`\>=2%
\catcode`\\=12|catcode`|{=12|catcode`|}=12%
|gdef|todoenv<|markdownReadAndConvert<\end{todo}><|end<todo>>>
|endgroup
```

you can then just use

```latex
\begin{todo}
Hello, *world*!
\end{todo}
```

as you probably indended. This is very similar to how `\begin{markdown} … \end{markdown}` is defined [in section 3.3.2 of the technical documentation](ctan.math.washington.edu/tex-archive/macros/generic/markdown/markdown.pdf#page=93).

**Comment by cdupont** [comment]
Thanks a lot.

**Comment by Witiko** [comment]
We may want to add support for easier use of the `markdown` LaTeX environment in other LaTeX environments using a similar approach as [`tabularx`][1]:

![image](https://github.com/Witiko/markdown/assets/603082/0259a08c-289d-4d1e-9267-93f00868b3e1)

 [1]: https://ctan.org/pkg/tabularx

**Comment by Witiko** [comment]
@cdupont In commit https://github.com/Witiko/markdown/pull/477/commits/9be9a8117bf2c53dfac29e4eb8c14021b489d5f1 from PR #477, I added support for user-defined LaTeX environments with LaTeX markup:

![image](https://github.com/user-attachments/assets/254072bf-2fd1-46de-a877-c3ed57222011)
