### ISSUE TITLE
Add `blankBeforeList` Lua option

### ISSUE THREAD

**Issue by akloeckner** [Witiko/markdown#29]
Currently, the markdown package recognizes lists only when they are preceded by a blank line (or some other block-finishing element, I suppose). However, the list is not recognized, if it directly follows a regular text. There is no consensus about the correct Markdown behavior in that case: Should there be a list? Or should the text be continued? The markdown package continues the text.

Example:
```
Some text
- List item 1
- List item 2
```

It would be great to have an option such as `blankBeforeBlockquote`, but `blankBeforeList` to control this behavior.

Here are a few notes by Vit just to keep them in the record:

> As for the leading blank line before lists, there is no consensus between different implementations of Markdown on this issue [1] [2], and the Markdown spec leaves the behavior unspecified [3]. 

 [1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=This+is+a+list%0A-+without+a+leading+blank+line.
 [2]: https://talk.commonmark.org/t/blank-lines-before-lists-revisited/1990
 [3]: https://daringfireball.net/projects/markdown/syntax#list

**Comment by Witiko** [comment]
Thank you for the report.

Here is some additional discussion [[4][]] regarding the issue. With a
text editor that does hard wrapping, it is easy to end up with an
asterisk, dash, or a number followed by a dot at the beginning of a line
by accident. Nevertheless, given the lack of consensus, this seems to be
a good candidate for a new Lua option.

 [4]: https://github.com/jgm/pandoc/issues/2748

**Comment by Witiko** [comment]
Thank you for the report.

Here is some additional discussion [[4][]] regarding the issue. With a text editor that does hard wrapping, it is easy to end up with an asterisk, dash, or a number followed by a dot at the beginning of a line by accident. Nevertheless, given the lack of consensus, this seems to be a good candidate for a new Lua option.

 [4]: https://github.com/jgm/pandoc/issues/2748

**Comment by Witiko** [comment]
Since there is already a lot of [planned features](https://github.com/Witiko/markdown/milestone/1) for version 2.6.0 and the TeX Live 2018 freeze at 2nd April is a hard deadline for the release, I may not be able to include the feature in 2.6.0.

Below are some implementation notes for me or anyone who would be willing to implement the new option:

- Much like `blankBeforeBlockquote`, `blankBeforeCodeFence`, and `blankBeforeHeading`, the new option (`blankBeforeList`) will need to alter the paragraph parser (see `larsers.fencestart`, `larsers.Endline`, and `larsers.Paragraph` in Section 3.1.5 of the [documentation][doc] for the Lua implementation).
- The option needs to be included in the `defaultOptions` table with the default value of `false` and documented in Section 2.1.2 of the [documentation][doc] for the Lua interface.
- The option needs to be included in the plain TeX interface (see Section 2.2.2.2 of the [documentation][doc]) and the LaTeX interface (see Section 2.3.2.1 of the [documentation][doc]).
- The option needs to be included in the `\markdownLuaOptions` macro that passes the plain TeX options to Lua (see Section 3.2.2 of the [documentation][doc]).
- A pair of tests similar to [blank-before-code-fence.test](https://github.com/Witiko/markdown/blob/master/tests/testfiles/lunamark-markdown/blank-before-code-fence.test) and [no-blank-before-code-fence.test](https://github.com/Witiko/markdown/blob/master/tests/testfiles/lunamark-markdown/no-blank-before-code-fence.test) needs to be added to the [tests/testfiles/lunamark-markdown](https://github.com/Witiko/markdown/tree/master/tests/testfiles/lunamark-markdown) directory.

The structure of the package and additional directions for contributors are included in the [README.md](https://github.com/Witiko/markdown#contributing) document:

> # Contributing #
> 
> Apart from the example markdown documents and tests, which are placed in the `examples/` and `tests/` directories, the complete source code and documentation of the package are placed in the `markdown.dtx` document, following the literate programming paradigm.
> 
> When the file `markdown.ins` is interpreted using a Unicode-aware TeX engine, such as XeTeX (`xetex markdown.ins`) or LuaTeX (`luatex markdown.ins`), several files are produced from the `markdown.dtx` document. In `markdown.dtx`, the boundaries between the produced files are marked up using a XML-like syntax provided by the [DocStrip][] plain TeX package.
> 
> Running the [LaTeXMK][LaTeXMK] tool on the `markdown.dtx` file (`latexmk markdown.dtx`) after the Markdown package has been installed typesets the documentation. In `markdown.dtx`, the documentation is placed inside TeX comments and marked up using the [ltxdockit][] LaTeX document class. Support
> for typesetting the documentation is provided by the [doc][] LaTeX package.
> 
>  [DocStrip]:  https://ctan.org/pkg/docstrip   (docstrip – Remove comments from file)
>  [LaTeXMK]:   https://ctan.org/pkg/latexmk    (latexmk – Fully automated LaTeX document generation)
>  [ltxdockit]: https://ctan.org/pkg/ltxdockit  (ltxdockit – Documentation support)
>  [doc]:       https://ctan.org/pkg/doc        (doc – Format LaTeX documentation)


[doc]: http://mirrors.ctan.org/macros/generic/markdown/markdown.pdf

**Comment by jbriales** [comment]
I was looking for this option, good to see it was already discussed and documented.
Is there any update or anyone considering working on enabling this option at this point? :)

**Comment by Witiko** [comment]
If this feature is to be added, it should be added before the TL2020 code freeze on 15 March.

**Comment by Witiko** [comment]
However, given the fact that using such an option may not be such a good idea, I consider this a low priority.

> With a text editor that does hard wrapping, it is easy to end up with an asterisk, dash, or a number followed by a dot at the beginning of a line by accident.
