### ISSUE TITLE
Support for markdown tables 

### ISSUE THREAD

**Issue by AnthonyEbert** [Witiko/markdown#32]
Thank you for providing this package! I tried to insert a markdown table into a latex document, the table below was not rendered. 

| Letters | Numbers |
| ----    | ---     |
|   a     |  1      |
|   b     |  2      |

Here is the tex file I wrote. 

```{latex}
\documentclass{article}

\begin{document}

\begin{markdown}

## A table

| Letters | Numbers |
| ----    | ---     |
|   a     |  1      |
|   b     |  2      |

\end{markdown}

\end{document}
```

The output came out like this `| Letters | Numbers | | —- | — | | a | 1 | | b | 2 |` when I ran `pdflatex -shell-escape file.tex`. 

Thanks again

**Comment by Witiko** [comment]
Hi,

tables currently are not supported by the Markdown parser. There are several workarounds you can use:

### CSV tables using [file transclusion](https://github.com/Witiko/markdown/issues/4)

```tex
\documentclass{article}
\usepackage{filecontents}
\usepackage[contentBlocks]{markdown}
\begin{document}
\begin{filecontents*}{table.csv}
Letters,Numbers
a,1
b,2
\end{filecontents*}
\begin{markdown}
# A table
/table.csv (Letters and numbers)
\end{markdown}
\end{document}
```
![screenshot_20180310_230344](https://user-images.githubusercontent.com/603082/37247166-768be9d0-24b7-11e8-9216-88d3b2da1ca1.png)

### Mixing Markdown with LaTeX
```tex
\documentclass{article}
\usepackage[hybrid]{markdown}
\begin{document}
\begin{markdown}
# A table
\begin{tabular}{cc}
  Letters & Numbers \\\\ \hline
  a & 1 \\\\
  b & 2
\end{tabular}
\end{markdown}
\end{document}
```
![screenshot_20180310_230344](https://user-images.githubusercontent.com/603082/37247205-30473f0a-24b8-11e8-977a-8f6ebfc49d7f.png)

**Comment by dvins** [comment]
Thank you for the work arounds but they do not solve the problem of streaming content, written in Markdown and using tables, into a larger Latex document. Is support for this an impossibility? Is this something that can be accomplished if a few of us sponsor the work?

**Comment by dvins** [comment]
What is the best email to contact you at to discuss sponsorship further? In terms of approach the first is best and preferred so can be leveraged in a system like ShareLaTex as an import library.

**Comment by Witiko** [comment]
You can reach me at witiko@mail.muni.cz.

Odesláno z mého chytrého telefonu Samsung Galaxy.
-------- Původní zpráva --------Od: David Vins <notifications@github.com> Datum: 18.01.19  4:47  (GMT+01:00) Komu: Witiko/markdown <markdown@noreply.github.com> Cc: Vít Novotný <witiko@gmail.com>, Comment <comment@noreply.github.com> Předmět: Re: [Witiko/markdown] Support for markdown tables  (#32) 
What is the best email to contact you at to discuss sponsorship further? In terms of approach the first is best and preferred so can be leveraged in a system like ShareLaTex as an import library.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Witiko/markdown","title":"Witiko/markdown","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Witiko/markdown"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dvins in #32: What is the best email to contact you at to discuss sponsorship further? In terms of approach the first is best and preferred so can be leveraged in a system like ShareLaTex as an import library."}],"action":{"name":"View Issue","url":"https://github.com/Witiko/markdown/issues/32#issuecomment-455418397"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Witiko/markdown/issues/32#issuecomment-455418397",
"url": "https://github.com/Witiko/markdown/issues/32#issuecomment-455418397",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Witiko** [comment]
Table support is now available in the `master` branch and will be published in version 2.8.0 by the end of April. See the following example:

```tex
\documentclass{article}
\usepackage[pipeTables, tableCaptions]{markdown}
\begin{document}
\begin{markdown}
| Right | Left | Default | Center |
|------:|:-----|---------|:------:|
|   12  |  12  |    12   |    12  |
|  123  |  123 |   123   |   123  |
|    1  |    1 |     1   |     1  |

  : Demonstration of pipe table syntax.
\end{markdown}
\end{document}
```

**Comment by rafaelzemog** [comment]
Hello I have been working with table support but I have two issues:
1.  The tables are misplaced eg. at the top of the page when they must be in the middle of the page.
2. I only have the horizontal lines displayed in the table nor the vertical ones.
```
### Documentos oficiales
\vspace{1cm}

| ID DOCUMENTO | DESCRIPCIÓN |
|:------------:|:------------------------------------------------|
| DOC-1        | Propuesta para el Proyecto Sistema Aéreo No Tripulado de Despegue y aterrizaje Vertical |
Table: Documentos oficiales de referencia


### Otras publicaciones técnicas, legales y referenciales
\vspace{1cm}

| ID DOCUMENTO | DESCRIPCIÓN                                                       |
|:------------:|-------------------------------------------------------------------|
| DOC-2        | Manual de Procesos del Sistema de Gestión de Calidad del INIDETAM |
Table: Otras publicaciones aplicables
```

![My oputput](https://user-images.githubusercontent.com/3085858/57186476-c0834b80-6ea5-11e9-9c48-9607fce91fa9.png)

**Comment by Witiko** [comment]
Hello @rafaelzemog,

let's have a look at your issues:

> 1. The tables are misplaced eg. at the top of the page when they must be in the middle of the page.

You can specify to LaTeX that it should not make tables float:

```tex
\usepackage{float}
\makeatletter
\renewcommand*{\fps@table}{H}
\makeatother
```

![Spectacle TJ7808](https://user-images.githubusercontent.com/603082/57192753-1c94b100-6f34-11e9-956b-3e98db708cea.png)

Alternatively, when you don't specify a caption, the default LaTeX table renderer will also prevent the table from floating:

```md
### Documentos oficiales
| ID DOCUMENTO | DESCRIPCIÓN |
|:------------:|:------------------------------------------------|
| DOC-1        | Propuesta para el Proyecto Sistema Aéreo No Tripulado de Despegue y aterrizaje Vertical |

### Otras publicaciones técnicas, legales y referenciales
| ID DOCUMENTO | DESCRIPCIÓN                                                       |
|:------------:|-------------------------------------------------------------------|
| DOC-2        | Manual de Procesos del Sistema de Gestión de Calidad del INIDETAM |
```
![Spectacle TJ7244](https://user-images.githubusercontent.com/603082/57192671-629d4500-6f33-11e9-8621-861c27ffeedd.png)

> 2. I only have the horizontal lines displayed in the table nor the vertical ones.

Omiting the vertical lines is generally prefered in modern typesetting. If you want to add horizontal lines, you will need to modify the default table renderer (or [write your own](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#table-renderer)):

```tex
\usepackage{markdown}
\makeatletter
\def\markdownLaTeXReadAlignments#1{%
  \addto@hook\markdownLaTeXTableAlignment{|}%
  \advance\markdownLaTeXColumnCounter by 1\relax
  \if#1d%
    \addto@hook\markdownLaTeXTableAlignment{l}%
  \else
    \addto@hook\markdownLaTeXTableAlignment{#1}%
  \fi
  \ifnum\markdownLaTeXColumnCounter<\markdownLaTeXColumnTotal\relax\else
    \addto@hook\markdownLaTeXTableAlignment{|}%
    \expandafter\@gobble
  \fi\markdownLaTeXReadAlignments}
\makeatother
```
![Spectacle TJ7808](https://user-images.githubusercontent.com/603082/57192854-78ac0500-6f35-11e9-94e1-6e84b4b6f974.png)

**Comment by rafaelzemog** [comment]
Thank you for your support.

**Comment by Witiko** [comment]
@awelormro This is not possible with the `pipeTables` syntax extension.

**Comment by fenggeorgeyu** [comment]
For the pipeline table in latex, is there any way the table caption can be on top of the table instead of under the table?  Thanks for helping.

**Comment by Witiko** [comment]
@fenggeorgeyu You can use LaTeX packages `float` and `caption` to control the placement and spacing of captions:

``` tex
\documentclass{article}
\usepackage[pipeTables, tableCaptions]{markdown}
\usepackage{float,caption}
\begin{document}

\floatstyle{plain}  % Setup float package to always put captions below tables
\restylefloat{table}
\captionsetup[table]{position=below}  % Setup caption package to place \abovetopsep between caption and table
\begin{markdown}
| Here is a header |
|------------------|
| Here is a row    |
: Here is a caption
\end{markdown}

\floatstyle{plaintop}  % Setup float package to always put captions above tables
\restylefloat{table}
\captionsetup[table]{position=above}  % Setup caption package to place \abovetopsep between caption and table
\begin{markdown}
| Here is a header |
|------------------|
| Here is a row    |
: Here is a caption
\end{markdown}

\end{document}
```

![scrot](https://user-images.githubusercontent.com/603082/211523117-17be0d7b-761f-4062-9dba-76d0cad7be8b.png)

Hope this helps! Please, use [Discussions][1] for future Q&A on this topic and any other topic.

 [1]: https://github.com/Witiko/markdown/discussions
