### ISSUE TITLE
Hybrid + latex comments => bug

### ISSUE THREAD

**Issue by jendas1** [Witiko/markdown#42]
Hi,
I have found out, when using hybrid mode, that the lines below comments disappear. Here is MWE
~~~~
\documentclass{article}

\usepackage[hybrid]{markdown}

\begin{document}
\begin{markdown}
% Comment
Hello _world_.

Second line.
\end{markdown}
\end{document}
~~~~
### Desired output
Hello _world_.
Second line.
### Actual output
Second line.

----
It is a really annoying bug, because there is no error nor warning if the next line after the comment is not blank. 
Is there an easy workaround in the lua code before the bug can be properly patched? Some latex construct are dependant on comments, so they can't just be stripped off.

https://www.sharelatex.com/read/ythksyknnwqb

**Comment by Witiko** [comment]
Hi,

thank you for reporting the issue. I am hesitant to call this a bug, since it is a feature of the Markdown parser and Markdown in general. During the conversion, newlines are not preserved unless they separate individual blocks or unless they are preceded by two or more white space characters, which then translates to a hard line break. [[1][blocks]]  Since the `hybrid` option just leaves plain TeX special characters alone, the use of TeX comments leads to the behavior you observe. I agree that it is an annoying feature and I am open to suggestions for solving it. I list a couple of workarounds below.

***

If you just want the ability to comment your document, you can use [the `html` option][html], which allows you to use HTML comments. As an added benefit, this makes your Markdown document a little easier to convert to HTML using tools such as [Pandoc][] or [MultiMarkdown][]. This would be your MWE using HTML comments:

``` latex
\documentclass{article}

\usepackage[hybrid, html]{markdown}

\begin{document}
\begin{markdown}
<!-- Comment -->
Hello _world_.

Second line.
\end{markdown}
\end{document}
```

***

As mentioned above, you can also insert hard breaks by preceding the newline with two or more white space characters, which partly solves your problem. However, you are required to use an external file, since TeX gobbles spaces at the ends of lines, and therefore removes all the hard breaks you typed in your document [[2][techdoc], sec. 2.2.1]. This would be your MWE using an external document:

``` latex
\documentclass{article}

\usepackage[hybrid]{markdown}

\begin{document}
\markdownInput{document.md}
\end{document}
```

This would be the external document named `document.md`. Notice the two spaces at the end of the first line:

``` latex
% Comment  
Hello _world_.

Second line.
```

This translates to the following intermediate representation:

```latex
% Comment\markdownRendererLineBreak
{}Hello \markdownRendererEmphasis{world}.\markdownRendererInterblockSeparator
{}Second line.\relax
```

This works by accident, since the hard line break command `\markdownRendererLineBreak` is followed by a newline. However, it does not leave the comment intact.

 [blocks]: https://daringfireball.net/projects/markdown/syntax#block (Daring Fireball: Markdown Syntax Documentation, Block Elements)
 [html]: http://mirrors.ctan.org/macros/generic/markdown/markdown.html#option-html (Markdown Package User Manual, option html)
 [techdoc]: http://mirrors.ctan.org/macros/generic/markdown/markdown.pdf (A Markdown Interpreter for TeX)
 [multimarkdown]: http://fletcherpenney.net/multimarkdown/ (MultiMarkdown)
 [pandoc]: http://pandoc.org/ (Pandoc – a universal document converter)

**Comment by jendas1** [comment]
I can see the reasoning behind not being a bug, but in the hybrid mode, I think such a basic construct as comment should keep its form and be a commend without any side effects.

Therefore I think modifying convert function that strips all comments should be definitely much better solution than joining it with a next line. 

Stripping the comments actually should not even brake any latex code at all (excluding special environments such as lstlisting which doesn't work with in the markdown environment either) cause the reason of putting an artificial comment is to strip the newline which will be stripped also using gsub.

Here is the code that should do the job (by just adding the 3 lines to a convert function, so the function looks like:

~~~~
  function self.convert(input)
    references = {}
    local opt_string = {}
    for k,_ in pairs(defaultOptions) do
      local v = options[k]
      if k ~= "cacheDir" then
        opt_string[#opt_string+1] = k .. "=" .. tostring(v)
      end
    end
    -- Added code
    if options.hybrid then
        input = string.gsub(input,"%%[^\n]*\n?","")
    end
    table.sort(opt_string)
    local salt = table.concat(opt_string, ",") .. "," .. metadata.version
    local name = util.cache(options.cacheDir, input, salt, function(input)
        return util.rope_to_string(parse_blocks_toplevel(input)) .. writer.eof
      end, ".md" .. writer.suffix)
    return writer.pack(name)
  end
~~~~

**Comment by jendas1** [comment]
I am not sure what is the problem, but I don't see any difference between the snippet when written inside the markdown with hybrid mode or normally in latex. https://www.sharelatex.com/read/ythksyknnwqb

**Comment by Witiko** [comment]
You are correct. I did not notice that you are stripping newlines as well. However, the solution is still easily broken:

\documentclass{article}

\usepackage[hybrid]{markdown}
\usepackage{listings}
\begin{document}
\subsection{LaTeX}
This is the paragraph number one.%

This is the paragraph number two.

100\\% Real: 100 Insanely Good Recipes For Clean Food Made Fresh
\subsection{Markdown}
\begin{markdown}
This is the paragraph number one.%

This is the paragraph number two.

100\\% Real: 100 Insanely Good Recipes For Clean Food Made Fresh
\end{markdown}
\end{document}

**Comment by jendas1** [comment]
Ok, a bit naïve about being it a simple fix. :D I am not used to the parser you have so I can’t add the functionality to the core. Moreover I don’t understand the rule with the LaTeX comments anymore. I thought they always catch a newline, but now they have exceptions (1st case)? Weird.

**Comment by Witiko** [comment]
The parser is [lunamark](https://github.com/jgm/lunamark) and it mainly uses the [LPEG](www.inf.puc-rio.br/~roberto/lpeg) Lua library that allows you to write a parser for PEG grammars. TeX always converts to newlines into a `\par` token; the overall behavior is a little involved, see the [TeXbook](www.ctex.org/documents/shredder/src/texbook.pdf) (chapter 8, mainly pages 46 and 47). Since TeX can be configured to make arbitrary characters start a comment, not just the percent sign, it may be more fruitful to make the parser keep newlines where they appear in the input rather than to try and parse TeX input.

**Comment by Witiko** [comment]
In b94dda5, I added an `iterlines` function, which I will use to solve both this issue and #75. Currently, none of the changes are accessible from outside Lua.

**Comment by Witiko** [comment]
I added the `stripComments` option in 857bd55. As always, alpha testing before release is welcome.

**Comment by Witiko** [comment]
I have briefly described the comment stripping algorithm [here][1]; I am planning to add more details in a future TUGboat article.

One thing that is bugging me about the current algorithm is that it is based on lexical preprocessing: the comments may appear anywhere in the code, even in e.g. code blocks or URLs, and the preprocessor will still strip them:

```` markdown
Here is some [link][].

 [link]: https://some.url/path%20with%20spaces (here is a title that will be stripped together with a part of the URL)

```
This is some code % here is a comment that will be stripped
    here are some leading spaces that will also be stripped.
```
````

Since is not always desirable, I am considering adding a semantic comment-stripping option, where the comments would be considered Markdown inline elements and disallowed whereever inline elements are disallowed. Here is what I am thinking the LaTeX user interface might look like:

```
\usepackage[stripComments=false]{markdown}     % Disable comment stripping, default
\usepackage[stripComments=true]{markdown}      % Enable semantic comment stripping, implicit
\usepackage[stripComments=semantic]{markdown}  % Enable semantic comment stripping, explicit
\usepackage[stripComments=lexical]{markdown}   % Enable lexical comment stripping
```

Feedback is welcome.

 [1]: https://www.overleaf.com/read/jcsntnkhqrfb

**Comment by Witiko** [comment]
@jendas1 I have briefly described the comment stripping algorithm [here][1]; I am planning to add more details in a TUGboat article.

One thing that is bugging me about the current algorithm is that it is based on lexical preprocessing: the comments may appear anywhere in the code, even in e.g. code blocks or URLs, and the preprocessor will still strip them:

```` markdown
Here is some [link][].

 [link]: https://some.url/path%20with%20spaces (here is a title that will be stripped together with a part of the URL)

```
This is some code % here is a comment that will be stripped
    here are some leading spaces that will also be stripped.
```
````

Since is not always desirable, I am considering adding a semantic comment-stripping option, where the comments would be considered Markdown inline elements and disallowed whereever inline elements are disallowed. Here is what I am thinking the LaTeX user interface might look like:

```
\usepackage[stripComments=false]{markdown}     % Disable comment stripping, default
\usepackage[stripComments=true]{markdown}      % Enable semantic comment stripping, implicit
\usepackage[stripComments=semantic]{markdown}  % Enable semantic comment stripping, explicit
\usepackage[stripComments=lexical]{markdown}   % Enable lexical comment stripping
```

Feedback is welcome.

 [1]: https://www.overleaf.com/read/jcsntnkhqrfb

**Comment by Witiko** [comment]
After mulling it over some more, I renamed `stripComments` to `texComments` in 92f217b and rejected the idea from https://github.com/Witiko/markdown/issues/42#issuecomment-817316693. Here is the rationale:

1. If you want Markdown-aware "semantic" comments, you can use the `html` option and use the HTML comments.
2. If you want Markdown-unaware "lexical" comments, you can use the `texComments` option and use the TeX comments.

Although it would be interesting to have two flavors of TeX comments, the HTML comments work well in practice and can be easily distinguished from TeX comments, i.e. we are not adding another opportunity for the users of the package to use vastly different dialects, where the intent of the markup cannot be meaningfully understood without knowing which options were used.

**Comment by Witiko** [comment]
Since the use of TeX comments in the plain TeX output is impossible anyways, perhaps we could set the catcode of the percent sign (`%`) to other (`\catcode`\%=12`) locally when we are typesetting markdown? This would make it easier to use TeX with the `hybrid` Lua option, see #79.
