### ISSUE TITLE
Multiple citations and citations with pretext and omissions not working

### ISSUE THREAD

**Issue by lukaskawerau** [Witiko/markdown#44]
Embedding a markdown file with multiple citations, pretext and omissions does not work as described in the documentation using Pandoc-style citations.
See [here](https://v2.overleaf.com/read/fqfwdmcbvmdv) for an example.

**Comment by Witiko** [comment]
What is the actual vs. expected output?

**Comment by Witiko** [comment]
Thank you for the report. The issue does not seem to be related to the Markdown parser itself, but rather to the default renderer for citations, which makes this low priority, since the default renderers are meant to be redefined by the user.

The lack of a space before “also" in “see (Gamson, 1975, pp. 33-35)also (Gamson, 1975, chap. 1)” is an easy fix (see technical documentation, sections [2.2.3.19](http://mirrors.ctan.org/macros/generic/markdown/markdown.pdf#page=26), and [3.3.4](http://mirrors.ctan.org/macros/generic/markdown/markdown.pdf#page=102)). I will give it a look during the next weekend, patches are welcome.

The remaining differences are due to the fact that Pandoc supports Natbib, whereas we do not. The default citation renderer for LaTeX is only aware of BibLaTeX and otherwise uses the built-in LaTeX `\cite` command, which does not support fancy citations (see technical documentation, Section [3.3.4](http://mirrors.ctan.org/macros/generic/markdown/markdown.pdf#page=102)). It would be neat to have a built-in support, patches are welcome.

**Comment by Witiko** [comment]
I just fixed the missing space before “also” in commit 274512772622f1c760a6188b56b5e4b901d2689b.

Before:
![before](https://user-images.githubusercontent.com/603082/41112084-41c49f32-6a7e-11e8-89a5-025eeebd26c2.png)

After:
![after](https://user-images.githubusercontent.com/603082/41112103-4c9e02b8-6a7e-11e8-995e-325843be29f3.png)

**Comment by Witiko** [comment]
I just added Natbib support in commit [`c82a821`](https://github.com/Witiko/markdown/commit/c82a82153b691984e87be4e37089da4f8c5c3714).

Natbib provides the `\citep` command for parenthetical citations, and the `\citet` command for text citations. When multiple citations are specified without prenotes, and postnotes, we will want to specify the citations in bulk:

```tex
- \citep{jon90,jon91,jon92,jon93}
- \citet{jon90,jon91,jon92,jon93}
```
![screenshot_20180628_231145](https://user-images.githubusercontent.com/603082/42060901-b0811710-7b28-11e8-9f36-f12f33d52abd.png)

Prenotes, and postnotes are also supported by Natbib:

```tex
- \citep[prenote][postnote]{jon90}
- \citet[prenote][postnote]{jon90}
```
![screenshot_20180628_231453](https://user-images.githubusercontent.com/603082/42061029-14328302-7b29-11e8-94fe-a27c4007047f.png)

However, we can't combine prenotes, and postnotes with bulk citations, because we need to support prenotes, and postnotes on the level of individual citations. Unlike BibLaTeX, Natbib does not really support this out-of-box:

```tex
- \citep[prenote][postnote]{jon90,jon91,jon92,jon93}
- \citet[prenote][postnote]{jon90,jon91,jon92,jon93}
```
![screenshot_20180628_231656](https://user-images.githubusercontent.com/603082/42061140-6a7b6260-7b29-11e8-8b9d-32e623b0cb37.png)

Here is what the Markdown package currently produces:
```tex
\documentclass{article}
\usepackage{natbib}
\usepackage[citations]{markdown}
\begin{document}
\bibliographystyle{plainnat}
\begin{markdown}
- [@jon90; @jon91; @jon92; @jon93]
- @jon90[; @jon91; @jon92; @jon93]
- [@jon90; @jon91; prenote @jon92 postnote; @jon93]
- @jon90[; @jon91; prenote @jon92 postnote; @jon93]
\end{markdown}
\begin{thebibliography}{1}
\bibitem[Jones et al.(1990)]{jon90}
\bibitem[Jones et al.(1991)]{jon91}
\bibitem[Jones et al.(1992)]{jon92}
\bibitem[Jones et al.(1993)]{jon93}
\end{thebibliography}
\end{document
```
![screenshot_20180628_231926](https://user-images.githubusercontent.com/603082/42061220-b6b49dc2-7b29-11e8-9e59-73b3ed8dc5e5.png)

**Comment by lukaskawerau** [comment]
This looks great! Will this make it into a release at some point? The last release was in April I think, so this is not available to use yet :)

**Comment by Witiko** [comment]
There will definitely be a release before TeX Live 2019.
