### ISSUE TITLE
Slice without explicit html attributes

### ISSUE THREAD

**Issue by niknetniko** [Witiko/markdown#54]
It is possible to use the slice option without using the explicit html attributes?

The reason I ask is that I have a markdown file I want to include in a latex document, but I can't make changes to the markdown file, since it is also used elsewhere, where the special syntax for html attributes is not supported.

I did find issue #28, but that syntax doesn't work (as is expected, since it's not in the user manual).

**Comment by Witiko** [comment]
> It is possible to use the slice option without using the explicit html attributes?

No, this is currently impossible. The approach drafted in #28 suffers from problems related to character escaping. A possible solution would be to support slicing based on the section numbers, although this would be a relatively brittle approach.

**Comment by niknetniko** [comment]
Would it perhaps be possible to create a default anchor, i.e. "My fancy markdown title" -> "my-fancy-markdown-title".

**Comment by Witiko** [comment]
Yes, that would be possible and probably also a good idea, thank you for the suggestion.

**Comment by Witiko** [comment]
The default anchor is also not completely straightforward to implement. A couple of obstacles that come to mind:

- Exotic unicode characters can be difficult to cast to ASCII and the user may not know what the default anchor is.
- Repeated headings would require some sort of numbering (i.e. “my-fancy-markdown-title-2”), which, again, makes it difficult for the user to know what the default anchor is.

**Comment by niknetniko** [comment]
I hadn't really thought about those case, but upon further reflection, I think it is probably best to do as little as possible automatically, i.e.
1. If the header cannot be converted due to weird unicode, referring to it would lead to an error. I haven't had a chance to look at the source code, but is it a requirement to have ascii anchors? If not, we could also use the same logic that is used when those unicode characters are encountered in the body of the markdown file, and allow that as anchors.
2. If two headers result in the same anchor and a user refers to it, it would error (or have the same behaviour as what happens now when you put the same anchor on two headings with html attributes).

If such an error is encountered, it would be up to the user to provide alternative anchors via the html attribute system that exists today. This way, there is minimal behaviour that would potentially surprise users.

As for how the user would know which header is what, perhaps an additional option can be provided, which would print the anchors with the headings, for example this code:
```markdown
### Introduction
#### Who am I?
```

Would, with `showAnchors=false`, result in
> ### Introduction
> #### Who am I?

While `showAnchors=true` results in
> ### Introduction (id: introduction)
> #### Who am I? (id: who-am-i)

(Of course, this is all just me talking, I haven't looked at the implementation, so no idea if it is feasible or even sensible). I should have some time starting next week to look at potentially implementing this, but my experience with Latex packages is limited, so it will probably take a while.

---
Slicing based on section numbers (or even based on line numbers) would also work in my case, but is indeed a bit fragile.

**Comment by Witiko** [comment]
> 1. If the header cannot be converted due to weird unicode, referring to it would lead to an error. I haven't had a chance to look at the source code, but is it a requirement to have ascii anchors? If not, we could also use the same logic that is used when those unicode characters are encountered in the body of the markdown file, and allow that as anchors.

It is not unsolvable, but we would need todisable the default LaTeX behavior, which is to expand non-ASCII characters into TeX macros, so that Lua does not receive a garbled anchor name. I am not currently certain how ConTeXt handles things. It can be done, but it would increase code complexity.

More importantly, though, spaces are considered to be separators in the value of `slice`, i.e. at least spaces would have to be replaced with dashes or another character.

> 2. If two headers result in the same anchor and a user refers to it, it would error (or have the same behaviour as what happens now when you put the same anchor on two headings with html attributes).

Currently, such behavior is undefined. I have not tested this corner case, but it is possible that, if you have two sections with the same id, both will be included in the slice as currently implemented.

> As for how the user would know which header is what, perhaps an additional option can be provided, which would print the anchors with the headings, for example this code: […]

Note that there is a posibility that the Markdown package will make use of other HTML attributes in the future. Therefore, it may be better to have a `showHeaderAttributes` option, which is consistent with [the current naming](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#header-attributes), and would dump all the attributes of a header.

> (Of course, this is all just me talking, I haven't looked at the implementation, so no idea if it is feasible or even sensible). I should have some time starting next week to look at potentially implementing this, but my experience with Latex packages is limited, so it will probably take a while.

A lot of this is feasible, see above. Best of luck with your efforts. I will be here if you need to discuss anything related to the implementation.

> Slicing based on section numbers (or even based on line numbers) would also work in my case, but is indeed a bit fragile.

We could produce several implicit header names, including section numbers:

```md
# My first heading
<!-- implicitly #section-1 -->
<!-- implicitly #my-first-heading -->
<!-- implicitly #my-first-heading-1 -->

## My second heading ##    {#bar}
<!-- not implicitly #section-1.1 since the user overrides #section-1.1 below -->
<!-- implicitly #my-second-heading -->
<!-- implicitly #my-second-heading-1 -->

## My second heading   {#section-1.1}
<!-- implicitly #section-1.2 -->
<!-- implicitly #my-second-heading -->
<!-- implicitly #my-second-heading-2 -->
```

Lua has support for so-called [metatables](https://www.lua.org/pil/13.html), which provide support for [prototypical inheritance](https://javascript.info/prototype-inheritance). Therefore, explicit anchor names can be stored in a higher-precedence table and implicit anchor names can be stored in its metatable, which implements the above behavior.

**Comment by Witiko** [comment]
> I can't make changes to the markdown file, since it is also used elsewhere, where the special syntax for html attributes is not supported.

Have you considered including the html attributes and stripping them before using them elsewhere? It may be a simpler task, all things considered.

**Comment by niknetniko** [comment]
> Have you considered including the html attributes and stripping them before using them “elsewhere”? It may be a simpler task, all things considered.

This seemed like a good idea to me, so I've done some investigating -- the external tool that uses my markdown file is implemented in Ruby and uses Kramdown, which supports the same syntax for header ids as this library, so problem solved 😄 Thanks a lot for the quick responses and the good idea!

Considering that adding this feature to this package introduces a fair amount of complexity and has some non-trivial problems, while the use case for such a feature is not that common, I'm not sure it is worth the effort.

**Comment by Witiko** [comment]
Glad to hear that your issue has been solved.

Although adding implicit anchor names is a nice idea, the implementation is non-trivial and would require further discussion. For now, I am closing this issue. If there is future demand, the issue can be reopened.
