### ISSUE TITLE
Cannot manage output directory

### ISSUE THREAD

**Issue by etienne-monier** [Witiko/markdown#57]
Hi,

### Problem
I cannot handle output directory correctly.

### Minimum working example

I have a directory whch looks like this.
```
+- test.tex
+- input.md
+- dir
|   + input.md
+- build
```
where both `input.md` just contains `#This is a test` and `test.tex` contains
```
\documentclass[]{article}

\def\filename{./dir/input.md}
% \def\filename{./input.md}

\usepackage{markdown}
% \def\markdownOptionOutputDir{./build}

\begin{document}

\markdownInput{\filename}

\end{document}
```

#### Test 1
When I run `pdflatex -shell-escape test.tex`, everything goes right and all output are in current dir, whatever is the `input.md`file used.

#### Test 2
When I run `pdflatex -shell-escape -output-directory=build test.tex` with the `input.md`file in current directory, I get a `test.markdown.out`file in current dir telling `Script file ./test.markdown.lua not found`, this file is inside the `build` directory.

#### Test 3
Same test with `\def\markdownOptionOutputDir{./build}` uncommented, I get an error in `pdflatex` telling 
```
! Package markdown Error: An error was encountered while executing Lua code.

See the markdown package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 ...amine the file "./build/test.markdown.err"}
```
with `build/test.markdown.err`saying `./build/test.markdown.lua:1: attempt to index a nil value`. Good point here: `test .markdown.out`is inside the `build dir`.

### Conclusion

I cannot process the file with every file inside the `build` directory without error.

Note: I have the latest version of Markdown and the 2019 version of TexLive.

Thanks for your help.

**Comment by Witiko** [comment]
Hello,

thank you for the detailed feedback. It appears that we assume that the input to `\markdownInput` is relative to `outputDir`, i.e. you would need to use `\def\filename{../dir/input.md}` or `\def\filename{../input.md}` with the current version of Markdown. However, this is definitely not desired or expected behavior.

The core of the issue is this: `\markdownInput` is a low-level command, which is used in the definition of the `\markdownReadAndConvert` command. The `\markdownReadAndConvert` command reads markdown code that is input directly from the TeX document (e.g. via `\begin{markdown} ... \end{markdown}` in LaTeX). For markdown code that is input directly from the TeX document, a temporary file is created in `outputDir`, whereas external markdown code input by the user via the `\markdownInput` command will not reside in `outputDir`.

I moved the decision-making about using / not using `outputDir` from `\markdownInput` to `\markdownReadAndConvert` in 81c9dae.
