### ISSUE TITLE
Support prenotes and postnotes with bulk citations

### ISSUE THREAD

**Issue by smartens** [Witiko/markdown#58]
Hi,
I'm using the markdown package to write my thesis with my university latex template. We have to use page number for citations and I often need to cite multiple authors. I wonder if there is any progress in terms of supporting this use case.

My latex template uses komascript as base and natbib but I have the option to enable biblatex support via class options. I saw that @Witiko mentioned in https://github.com/Witiko/markdown/issues/44#issuecomment-392537162 that "The default citation renderer for LaTeX is only aware of BibLaTeX and otherwise uses the built-in LaTeX \cite command, which does not support fancy citations". Does that mean if I use biblatex I could use this feature?

**Comment by Witiko** [comment]
Hello,

> "The default citation renderer for LaTeX is only aware of BibLaTeX and otherwise uses the built-in LaTeX \cite command, which does not support fancy citations"

This is outdated information, the package supports both Natbib and BibLaTeX since [version 2.7.0](https://github.com/Witiko/markdown/releases/tag/2.7.0) (c82a82153b691984e87be4e37089da4f8c5c3714).

> Does that mean if I use biblatex I could use this feature?

You can use either BibLaTeX or Natbib. The text citations (“@doe97 claims that …”) as well as parenthesized citations (“… was shown to cause X [@doe97, Section 1.2.3].”) will be rendered using the citation commands of whichever backend (BibLaTeX, Natbib, none) you have currently loaded.

For more examples, please refer to [the user manual](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#option-citations).

**Comment by smartens** [comment]
Thanks for the answer,

my template is using natbib as default. So I had problems with citations like e.g.: [@doe99, 45; @doe01, 56] and @doe99 [22].

I switched to the biber backend (thankfully my university template is providing such an option :P ).

As my problem with prenotes and postnotes is solved I'm closing this issue.
