### ISSUE TITLE
Could I get rid of the special meaning of backslash in markdown?

### ISSUE THREAD

**Issue by ngocbh** [Witiko/markdown#61]
I am using markdown in latex to note faster and I also have the notes in two formats (latex -> pdf and markdown). But it is annoying when I have to use `x\_i` to write `x_i` in latex. I also have to remove all of those slashes when copying to latex format. Could I rerender the underscore `_` in markdown where I want it to have no special meaning? 

I see the option when we can rerender heading like this:
`\markdownSetup{`
`   renderers = {`
`     headingOne = {\section{#1}},`
`     headingTwo = {\subsection{#1}},`
`. },`
`}`

But I don't know how to do in my case, Could you help me?

**Comment by Witiko** [comment]
You can set [the `underscore`option](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#option-underscores) to `false`.

**Comment by ngocjr7** [comment]
Amazing!! Thank you

**Comment by ngocjr7** [comment]
@Witiko Can I do the same thing with `backslash \`. It seems to be unnecessary in my case. I mean maybe I do not need to escape anything in markdown special character. I usually use the backslash in math equations instead. I search in your document but have not found the that option.

**Comment by Witiko** [comment]
Sorry, there is currently no such option. However, in most cases, you should be able to use a single backslash. Can you show an example where you need several backslashes to achieve what you need?

**Comment by ngocjr7** [comment]
Most cases I need to escape the backslash is when I need to use the backslash to escape other characters in latex formula. For example, I have to use `\\\\` to create a new line rather than `\\`, `\\[\\]` instead of `\[\]` or '\\{' instead of '\{'. It led me to fix the formula when I switched to latex. If you have the option to get rid of the special meaning of backslash in markdown, it will help me a lot when writing in hybrid mode.

**Comment by Witiko** [comment]
Such option is not yet implemented to the Lua parser. I will leave this issue open if anyone has the time and inclination to implement it.

**Comment by ngocjr7** [comment]
another example: 
hybrid mode in markdown
```
\\[distance[i] = 
    \begin{dcases}
        a & b \\\\\\
        c & d
    \end{dcases}
\\]
```
in latex:
```
\[distance[i] = 
    \begin{dcases}
        a & b \\
        c & d
    \end{dcases}
\]
```

I don't know why but I have to use six backslashes instead of four to make it work.

**Comment by Witiko** [comment]
> I have another question:
>
> I am writing in .md file and embed to latex by using \markdownInput{ option. Could I have something like \stopmarkdown or \starttex option in markdown to begin latex mode in .md file.
>
> For example:
>
> ```tex
> \starttex
> \[distance[i] = 
>     \begin{dcases}
>         a & b \\
>         c & d
>     \end{dcases}
> \]
> \stoptex
> ```

Not at the moment, but you can go the other way around, for example:

main.tex
> ```tex
> \input my-document
> ```

my-document.tex
> ```tex
> \begin{markdown}
> some markdown text
> \end{markdown}
> \[distance[i] = 
>     \begin{dcases}
>         a & b \\
>         c & d
>     \end{dcases}
> \]
> \begin{markdown}
> some other markdown text
> \end{markdown}
> ```

**Comment by rconnorlawson** [comment]
Another example of this is when using the '#' character, which always has to be escaped in LaTeX. I use the LaTeX markdown environment with option `hybrid=true`.

What works now:
```latex
\begin{markdown}
    RRT$^\\#$ is a motion planner.
\end{markdown}
```

What I would prefer:
```latex
\begin{markdown}
    RRT$^\#$ is a motion planner.
\end{markdown}
````

In this case, the option to turn off escaping of backslashes only within TeX math mode would be sufficient. 

Excellent package, by the way!

**Comment by Witiko** [comment]
@rconnorlawson The `#` character is special, since it starts headings. Therefore, Lunamark allows you to escape it as follows:

```markdown
# A heading
\# Not a heading
```

However, Lunamark it not smart enough to only allow escaping in places where a heading may meaningfully start. This is a more general issue and appears with all sorts of other symbols such as @, which starts citations, and others. Redoing this aspect of Lunamark would impact existing documents and it is best saved for the next major release.

**Comment by nicofranzp** [comment]
Any idea if this is happening soon?  I'm also having trouble with math environments and line breaks (`\\\\`).

**Comment by Witiko** [comment]
I am not tackling this at the moment, since it would require that we try to parse LaTeX and separate text from math, which can never be done precisely, since LaTeX is turing-complete. If we were to implement this, we would at least need a heuristic (e.g. anything between `$ $`, `$$ $$`, `\[ \]`, and `\begin{equation} \end{equation}` is math, all else is text), which is well-defined and reasonably compatible with whatever other markdown parsers are using.

**Comment by yfzhao20** [comment]
Nice package I think! Recently I have made some attempts about `hybrid` setting and other. Here are the results:

-  `_` mark

``` tex
\documentclass{ctexart}
\usepackage{markdown}

\begin{document}
\begin{markdown}

undefined_object

\end{markdown}
\end{document}
```

It works! ✅

![image](https://user-images.githubusercontent.com/80528249/128992487-05bf4259-a369-4956-bd6f-b29490453cd7.png)

But after I enable "hybrid"  option...

``` tex 
\documentclass{ctexart}
\usepackage{markdown}
\markdownSetup{hybrid = true}

\begin{document}
\begin{markdown}

undefined_object

\end{markdown}
\end{document}
```

ummmm🤔......It gives a bunch of errors:

![image](https://user-images.githubusercontent.com/80528249/129066304-3371cf5f-555b-49e7-a59c-a4159f65cfc4.png)

Obviously it treats `_` as subscript note in math environment. And at the same time `underscores` option fails.

I think it should be treated as markdown character but not math note if not in math environment, even `hybrid` enabled.  Maybe it shold distinguish math environment (`$$ $$`, `$ $`, `\[ \]`. `\( \)`) firstly......

- So does `^` note

- But when using math environment, I have to replace `\\` with `\\\\`... That is too much trouble to easily copy my markdown files into LaTeX documents...

- So I think the most important task is find the appropriate occasion to... to treat the "code" as LaTeX when `hybrid` option is open. Most of that are math environments. Maybe a lot of users don't  write markdown directly in LaTeX editor but copy from other .md files.

By the way, fantastic and awesome package I think! Thank you nice developer🎉.

**Comment by Witiko** [comment]
> I think it should be treated as markdown character but not math note if not in math environment, even `hybrid` enabled. Maybe it shold distinguish math environment (`$$ $$`, `$ $`, `\[ \]`. `\( \)`) firstly......

@yfzhao20 Thank you for your thoughts. Here is why I am not in favor of making `hybrid` any smarter:

- The Markdown package makes it extremely easy to switch between markdown and TeX,
- Using TeX commands hinders reusability of markdown documents in multitarget publishing.

Instead of making `hybrid` smarter, I would like to gradually phase out its use by introducing syntax extensions that address the common uses of TeX:

- TeX comments are useful for commenting-out and word wrap, so we introduced the `texComments` option in [version 2.10.0](https://github.com/Witiko/markdown/releases/tag/2.10.0).
- The `\label` and `\ref` LaTeX commands are indispensable for cross-refencing in academic texts, so we plan to #91, so that such functionality is available directly from within markdown.

Similarly, we could introduce a `math` Lua option, which would recognize common math environments (`$$ $$`, `$ $`, `\[ \]`, `\( \)`) and make it possible to use `^`, `_`, and `\\` in them. This option would be independent on `hybrid` and it would not claim to detect whether math mode is used in TeX (which is generally impossible due to TeX being only recursively enumerable). As discussed in https://github.com/Witiko/markdown/issues/61#issuecomment-796173217, such an option should strive for compatibility with whatever heuristics other markdown parsers such as Pandoc use to parse math.

**Comment by yfzhao20** [comment]
> > I think it should be treated as markdown character but not math note if not in math environment, even `hybrid` enabled. Maybe it shold distinguish math environment (`$$ $$`, `$ $`, `\[ \]`. `\( \)`) firstly......
> 
> @yfzhao20 Thank you for your thoughts. Here is why I am not in favor of making the `hybrid` option any smarter than it is now

Options with specific functions (LaTeX comment, math environment and so on) are indeed what I want! That's great🎉

> In LaTeX, you can specify the amount of vertical skip after a line break as follows: \\[2em]. Should Markdown be smart, detect that [2em] is not a link, and produce "\\[2em]" or should Markdown be predictable and produce "\[2em]"? Most markdown parsers seem to go with the latter approach, which is that \\ resolves to "\" regardless of the right context. Counterexamples are welcome.

 By the way, what I means about `\\` to `\\\\` is also about math environment (but not common markdown text). It seems that the problem will be solved with `math` option 😀

Cheers!

**Comment by Witiko** [comment]
@yfzhao20 I have given this some thought and I see two options:

1. We implement an option similar the [the `tex_math_dollars`][1] option of Pandoc.
2. We do our own thing. 😆 

 [1]: https://pandoc.org/MANUAL.html#extension-tex_math_dollars

**Comment by Witiko** [comment]
[The `tex_math_dollars` syntax extension][3] of Pandoc (see [1], [2] for implementation details) passes through inline and display math unchanged. Personally, I think that disallowing markdown markup inside math is a lost opportunity, because Markdown renderers [can take different actions][4] inside and outside math mode.

We could make a lot of users happy just by disabling underscores in math. However, allowing the users to type `\\` as `\\` instead of `\\\\` is trickier. We could make the parser smarter, so that it passes through a sequence of `\`s unchanged unless either:

1. 2k `\`s are followed by an escapable character, which would produce k `\`s.
2. 2k+1 `\`s are followed by an escapable character, which would produce k `\`s and the escaped character.

However, this still requires the users to type `\\[2em]` as `\\\\[2em]` unless we disabled links and footnotes inside math. Well, we can do just that. Therefore, the alternative solution to implementing the `tex_math_dollars` syntax extension of Pandoc would be:

1. Add a `smartBackslashes` Lua option that uses the above algorithm for escaping backslashes the smart way.
2. Add a `texMathDollars` Lua option. Like the `tex_math_dollars` syntax extension of Pandoc, the option would detect inline and display math in markdown text. Unlike the syntax extension, the Lua option would not pass the input through unchanged, but it would parse markdown markup with the exception of underscores, links, and footnotes. 

 [1]: https://github.com/jgm/pandoc/blob/60974538b25657c9aa37e72cc66ca3957912ddec/src/Text/Pandoc/Parsing.hs#L679
 [2]: https://github.com/jgm/pandoc/blob/60974538b25657c9aa37e72cc66ca3957912ddec/src/Text/Pandoc/Readers/LaTeX/Math.hs
 [3]: https://pandoc.org/MANUAL.html#extension-tex_math_dollars
 [4]: https://github.com/Witiko/markdown/commit/35b53d38b731c195a686cfad111ab3702d13844f

**Comment by Witiko** [comment]
We should also prevent code blocks in math.

**Comment by yfzhao20** [comment]
Can the issue be solved soon?🤝 I think this is the main reason that blocks me turning to LaTeX from markdown.. Unfortunately I'm not so good at Lua and maybe can not make some contributions to this project...

![image](https://user-images.githubusercontent.com/80528249/191880532-934afa14-dcc2-4bcd-a5df-284d29c4bb4d.png)

**Comment by Witiko** [comment]
@yfzhao20 I am sorry to say that there are always tasks of higher priority for me to work on. However, recently, the upstream lunamark library has received support for [raw attributes](https://pandoc.org/MANUAL.html#extension-raw_attribute) (see https://github.com/jgm/lunamark/pull/36), which I plan to port in October (see https://github.com/Witiko/markdown/issues/173). You could use raw attributes for typing mathematical formulae:

````` markdown
Here is a mathematical formula:
``` {=tex}
\[distance[i] = 
    \begin{dcases}
        a & b \\
        c & d
    \end{dcases}
\]
```
`````

Alternatively, you can contribute code or [sponsor][1] this issue. 🙂 

 [1]: https://github.com/sponsors/Witiko?frequency=one-time&sponsor=Witiko

**Comment by yfzhao20** [comment]
@Witiko Thanks for your effort !!! 🌹 I will try this feature later, and keep updating debug report. 😃

**Comment by Witiko** [comment]
In Markdown 2.18.0 (to be released on Monday), the `raw_attribute` option will be added that can be used to write mathematical formulae:

```` tex
\documentclass{article}
\usepackage[fenced_code, raw_attribute]{markdown}
\usepackage{mathtools}
\begin{document}
\begin{markdown}
Here is a `\TeX`{=tex} formula:
``` {=tex}
\[distance[i] = 
    \begin{dcases}
        a & b \\
        c & d
    \end{dcases}
\]
```
\end{markdown}
\end{document}
``````````

**Comment by Witiko** [comment]
In Markdown 2.21.0 (released in February 2023), the `tex_math_dollars` option has been added that can be used to write math:

```tex
\documentclass{article}
\usepackage[raw_attribute, tex_math_dollars]{markdown}
\usepackage{mathtools}
\begin{document}
\begin{markdown}
Here is a `\TeX`{=tex} formula:
$$distance[i] = 
    \begin{dcases}
        a & b \\
        c & d
    \end{dcases}
$$
\end{markdown}
\end{document}
```

**Comment by Witiko** [comment]
In Markdown 2.21.0 (released in February 2023), the `tex_math_single_backslash` (and `tex_math_double_backslash`) option has been added that can be used to write inline and display math surrounded by backslash-escaped parens and brackets, respectively:

```tex
\documentclass{article}
\usepackage[raw_attribute, tex_math_single_backslash]{markdown}
\usepackage{mathtools}
\begin{document}
\begin{markdown}
Here is a \(\text{\TeX}\) formula:
\[distance[i] = 
    \begin{dcases}
        a & b \\
        c & d
    \end{dcases}
\]
\end{markdown}
\end{document}
```

**Comment by Witiko** [comment]
The issue seems solved with multiple approaches to writing math described in https://github.com/Witiko/markdown/issues/61#issuecomment-1295963534, https://github.com/Witiko/markdown/issues/61#issuecomment-1462955587, and https://github.com/Witiko/markdown/issues/61#issuecomment-1462959435. Therefore, I am closing the issue.
