### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by mmarras** [Witiko/markdown#75]
Markdown parses tabs, latex does not. This can be tricky at times. 

A feature request concerning this is to get a reference level of tabs as a baseline, so latex code could still be properly indented. 

What I mean is best explained an example:

```
[...]
\begin{document}
\begin{markdown}
_emph_
\end{markdown}
\end{document}
```
works as expected and prints _emph_

```
[...]
\begin{document}
    \begin{markdown}
    _emph_
    \end{markdown}
\end{document}

```
does not and prints `_emph_` instead. 

Ideally one would be able to write:

```
[...]
\begin{document}
    \begin{markdown}
        _emph_
    \end{markdown}
\end{document}

```
Therefore ignore all tabs that are part of the latex code indentation but not of the markdown.

**Comment by Witiko** [comment]
Thanks for the idea. It's difficult to know at what level of indentation a markdown command starts. If anyone has an idea for how this could be implemented, I am willing to help with the implementation.

**Comment by mmarras** [comment]
I understand it could be hard to capture the necessary indent level, especially since it even depends on stuff that is happening outside the markdown environment. Maybe in absence of any brilliant idea, the dumb solution would be to provide a manual solution ala

```
    \begin{markdown}[baseindent=8]
        #Header 
    \end{markdown}
``` 
Another idea is that to make it the default expected behavior that the first line in the markdown is never indented (I cannot think of why the first one should be) and make a manual fix in case it has to be `[firstlineindent=True]`.

**Comment by Witiko** [comment]
I think the `firstlineindent` idea has edge cases, which are worth discussing. Consider a markdown document that starts with a list:

``` md
 - first item
 - second item
 - third item
```

In this case, the author would be forced not to use an additional space before the (first) bullet point, otherwise the indent would be shifter by a single space. This would not be an issue if we indented by "levels", i.e. the indentation would shift only after four spaces? This would solve the issue with the list, but you could still not start a document with a verbatim block. I don't think many users would be affected, but it is something to consider.

**Comment by mmarras** [comment]
Unfortunately, I'm not that experienced with markdown to discuss edge cases with much confidence. I'm coming more from the LaTeX side of things.

**Comment by adityam** [comment]
FWIW, see the option to [strip leading white space in the filter module](https://github.com/adityam/filter#stripping-leading-whitespace-mkiv-only). This relies on an internal context feature to strip leading white space (which is easy to implement after the entire environment has been passed on to lua).

**Comment by Witiko** [comment]
Interesting. However, stripping whitespace inside the environment is not a problem even without ConTeXt. What is a problem is capturing the indent level of the `\startmarkdown` command. Using the inner indent instead of the outer indent makes it impossible to typeset sole code blocks, among other things.

**Comment by Witiko** [comment]
The change would not be done on the level of Markdown, but on the level of the Lua parser. We would first strip the indent and only then we would invoke LPEG. I am thinking that a similar approach might also solve #42.

**Comment by adityam** [comment]
> Using the inner indent instead of the outer indent makes it impossible to typeset sole code blocks, among other things. However, I am thinking that this might be an acceptable trade-off.

Yeah, that is a corner case and has an easy workaround (using ` ``` ` instead of spaces to mark the code environment)

**Comment by Witiko** [comment]
@adityam Would you like to tackle this, or should I have a look? :slightly_frowning_face:

**Comment by adityam** [comment]
@Witiko I am not too familiar with the code base (and more importantly, how to test if the changes don't break anything; I have only used the package a few times for testing). So, unfortunately, I'll not be able to tackle this.

**Comment by Witiko** [comment]
> I am not too familiar with the code base

@adityam The high-level structure of the package is described in [a TUGboat article][2]. See also [notes for contributors in README][3].

> (and more importantly, how to test if the changes don't break anything; I have only used the package a few times for testing)

This should not be an issue, since there is continuous integration set up, i.e. GitHub would let you know if anything broke after each commit. You can also run the tests manually in [the tests/ directory][1].

> So, unfortunately, I'll not be able to tackle this.

That's a pity. However, if you were feeling adventurous, let me know. I don't think I will get to implementing in the next few weeks.

 [1]: https://github.com/Witiko/markdown/tree/master/tests
 [2]: https://www.tug.org/TUGboat/tb38-2/tb119novotny.pdf
 [3]: https://github.com/Witiko/markdown#contributing

**Comment by Witiko** [comment]
I added a first draft of the implementation in b94dda5. Currently, none of the changes are accessible from outside Lua.

**Comment by Witiko** [comment]
I added the `stripIndent` option in 4f7a190. As always, alpha testing before release is welcome.
