### ISSUE TITLE
Weird italics and emphasis

### ISSUE THREAD

**Issue by jendas1** [Witiko/markdown#9]
Hi,
I tried just the basics of markdown and I encountered weird behaviour of bold and italic text. 
`**this is bold**` is not only bold but also in italics. 
Here is the MWE (minimal non-working example)  on sharelatex:
https://www.sharelatex.com/project/5862e9f62ff353be2d9553fa

PS: Thank you so much for your work, I was searching for this interoperability with markdown for years.

**Comment by Witiko** [comment]
Hello,

double asterisks / underscores mark up strong emphasis. This markup is logical and does not need to be rendered using a bold face. In fact, these are the default LaTeX renderers for emphasis (single asterisks / underscores) and strong emphasis defined by the package:
```latex
emphasis = {\emph{#1}},
strongEmphasis = {%
    \ifx\alert\undefined
        \textbf{\emph{#1}}%
    \else % Beamer support
        \alert{\emph{#1}}%
    \fi},
```

Feel free to redefine these as you see fit:

```latex
\markdownSetup{
    renderers = {
        strongEmphasis = {\textbf{#1}},
    }
}
```

**Comment by Witiko** [comment]
You may even set up a more intricate behaviour that switches between the bold and medium faces when you \*\***nest**\_\_the\*\***strong**\*\*emphasis\_\_\*\*:

```latex
\newif\ifnestedstrong
\nestedstrongfalse
\markdownSetup{
    renderers = {
        strongEmphasis = {%
          \ifnestedstrong
            \nestedstrongfalse
            \textmd{#1}%
            \nestedstrongtrue
          \else
            \nestedstrongtrue
            \textbf{#1}%            
            \nestedstrongfalse
          \fi
        },
    }
}
```

Perhaps I shuld use something similar as the default rendererfor the strong emphasis, since it is closer to the behavior one would expect. This is why you should redefine the renderers that you expect to render in a specific manner, since the defaults are subject to change. The package manual is clear on that point, although I try to keep such changes to a minimum.

**Comment by jendas1** [comment]
Thank you for a clarification. I was just confused when I tried basics of markup and got "_wrong_" result (different visualisation than I expected).  I thing that your proposed solution is much better because people familiar with markdown would expect bold as a strongEmphasis rather than with italics as well.
